baseURL: "https://kgmyshin.blog"
title: kgmyshin log
paginate: 5
theme: PaperMod
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: kgmyshin log
  description: "kgmyshin"
  keywords: [Blog, Portfolio, PaperMod]
  author: kgmyshin
  # author: ["Me", "You"] # multiple authors
  images: ["profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "profile.jpg"
    favicon16x16: "profile.jpg"
    favicon32x32: "profile.jpg"
    apple_touch_icon: "profile.jpg"
    safari_pinned_tab: "profile.jpg"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "kgmyshin"
    imageUrl: "profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
  socialIcons:
    - name: twitter
      url: "https://twitter.com/kgmyshin"
    - name: github
      url: "https://github.com/kgmyshin"
    - name: note
      url: "https://note.com/kgmyshin"
    - name: email
      url: "https://kgmyshin.jp/contact/"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/kgmyshin/kgmyshin-log/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - resume:
      name: resume
      url: https://bit.ly/3z62dyw
      weight: 30
    - identifier: site
      name: site
      url: https://kgmyshin.jp/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
