name: Daily Memo
description: 日々感じたことメモ、ネタ
title: "[日々メモ]: "
labels: ["memo"]
projects: ["kgmyshin/5"]
assignees:
  - kgmyshin
body:
  - type: textarea
    id: memo
    attributes:
      label: 思ったこと
      description: 思ったことや感想を記入してください
    validations:
      required: true
