name: Good Article
description: 良かった記事
title: "[記事]: "
labels: ["article"]
projects: []
assignees:
  - kgmyshin
body:
  - type: input
    id: title
    attributes:
      label: Article Title
      description: 記事のタイトルを記入してください
      placeholder: 記事のタイトル
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: 記事のリンクを記入してください
      placeholder: Link
    validations:
      required: true
  - type: textarea
    id: review
    attributes:
      label: 要約や感想
      description: 要約や感想を記入してください
    validations:
      required: false
